$(document).ready(function(){thisPage.init();$(window).load(function(){thisPage.run()})});
var thisPage={init:function(){$("#calendarSelect select option:first").attr("selected",!0);$("#calendarSelect select").change(thisPage.calendarSelected);$("#calendarHeader #importButton").click(thisPage.budgetImport);$("#calendar .month .day").click(thisPage.dayClick);$("#header #searchButton").click(thisPage.search);$("#searchResultsContainer .label .title .ui-icon").click(thisPage.employmentTypeSelect);$("#header #searchQuery").keypress(function(a){a.which=="13"&&$("#header #searchButton").click()});
$("#calendarHeader textarea").keypress(function(a){a.ctrlKey&&a.shiftKey&&a.which=="13"&&$("#calendarHeader #importButton").click()});var a=$(".ui-button");a.mousedown(thisPage.mouseDown);a.mouseup(thisPage.mouseUp);a.hoverIntent(thisPage.hoverOn,thisPage.hoverOff);a=$("#searchResultsContainer .label #icon");a.mousedown(thisPage.mouseDown);a.mouseup(function(){$(this).removeClass("ui-state-active");var a=$(this).children(".ui-icon");a.hasClass("ui-icon-triangle-1-s")?thisPage.showSearchResults():
a.hasClass("ui-icon-triangle-1-n")&&thisPage.hideSearchResults()});a.hoverIntent(thisPage.hoverOn,thisPage.hoverOff);$("#calendar .year .ui-icon-circle-triangle-e").click(function(){var a=parseInt($("#calendar .year .text").html());thisPage.yearChange(a+1)});$("#calendar .year .ui-icon-circle-triangle-w").click(function(){var a=parseInt($("#calendar .year .text").html());thisPage.yearChange(a-1)});$("#calendar .month .day").bind("contextmenu",thisPage.displayDayMenu);$("#appNavBar #moreNavItem .ui-icon").click(function(){menuItemList=
[];menuItemList.push({name:"CSV Import "+$("#searchResultsContainer .label .title .text").html(),action:thisPage.csvImport,data:{}});menuItemList.push({name:"CSV Export "+$("#searchResultsContainer .label .title .text").html(),action:thisPage.csvExport,data:{}});thisPage.displayPopupMenu(this,menuItemList)});thisPage.initDialog();thisPage.loadMasterCalendar();$("#appNavBar #userNavItem").click(thisPage.displayUserMenu);$("input[type=text], select").focus(function(){$(this).addClass("auraSelected")});
$("input[type=text], select").focusout(function(){thisPage.clearAura($(this))});$("#searchResultsContainer .tableContainer").resizable({handles:"s",maxHeight:500})},initDialog:function(){$("#addAbsenceDialog .ui-state-error").tooltip({effect:"slide",relative:!0});var a=$("#addAbsenceDialog #nameField select");a.focus(function(){$(this).css("width","auto");$("#addAbsenceDialog #nameField input").css("width","20px")});a.change(function(){$("#addAbsenceDialog #nameField input").val("");$(this).val()==
"newCalendar"&&$("#addAbsenceDialog #nameField input").focus()});$("#addAbsenceDialog #nameField input").focus(function(){$(this).css("width","auto");$("#addAbsenceDialog #nameField select").css("width","20px");$("#addAbsenceDialog #nameField select option[value='newCalendar']").attr("selected",!0)});$("#addAbsenceDialog").dialog({title:"Absence",minWidth:500,autoOpen:!1,closeOnEscape:!0,modal:!0,resizable:!1,open:function(){$(".ui-dialog button span").removeClass("ui-button-text");var a=parseInt($("#calendar .year .text").html());
$("#addAbsenceDialog .year").val(a);var c=parseInt($("#calendar #selectedMonth").val()),d=parseInt($("#calendar #selectedDay").val()),a=new Date(a,c,d);$(".ui-dialog .date").html(a.toDateString());$(".ui-dialog .employmentType").html($("#searchResultsContainer .label .title .text").html());a=$("#addAbsenceDialog #nameField select");a.html($("#calendarHeader #calendarSelect select").html());a.children(":first").after('<option value="newCalendar">New Calendar</option>');$("#addAbsenceDialog .ui-state-error").hide();
$("#addAbsenceDialog #nameField input").val("");$("#addAbsenceDialog #rnField input").val("");$("#addAbsenceDialog #hoursField input").val("");c=$("#calendarSelect select option:selected").val();c!=""&&c!="newCalendar"&&a.children("option[value='"+c+"']").attr("selected",!0);$("#searchResultsContainer .label .title .text").html().trim()=="Teachers"?$("#addAbsenceDialog #hoursField").parent("tr").hide():$("#addAbsenceDialog #hoursField").parent("tr").show()},buttons:{Add:function(){var a=$("#addAbsenceDialog table select option:selected").html(),
c=$("#searchResultsContainer .label .title .text").html(),d=$("#addAbsenceDialog table .name").val(),e=a!="Master Calendar",f=isEmpty(d),g=$("#addAbsenceDialog table td #nameError"),h="",j=$("#addAbsenceDialog #nameField select"),k=$("#addAbsenceDialog #nameField .name"),m=$("#addAbsenceDialog #rnField .rn");if(a=="Master Calendar")$("#addAbsenceDialog #nameField .tooltip").html("Please select a calendar or create new one."),g.show(),thisPage.clearAura(j),thisPage.clearAura(k),j.addClass("auraRed");
else if(a=="New Calendar"){var l=d.split(","),h=/^[A-Z, ]+$/g,e=(e=(e=(e=e&&l.length==2)&&d.match(h)!=null)&&d.length>0)&&!f;e||($("#addAbsenceDialog #nameField .tooltip").html("Only letters, spaces, and a single comma allowed.<br><br>Example: LAST, FIRST"),g.show(),thisPage.clearAura(j),thisPage.clearAura(k),k.addClass("auraRed"))}else g.hide(),thisPage.clearAura(j),thisPage.clearAura(k);g=$("#addAbsenceDialog table .rn").val();j=$("#addAbsenceDialog table td #rnError");l=isEmpty(g);h=/^[0-9]+$/g;
(k=!l&&g.match(h))?(j.hide(),thisPage.clearAura(m)):(j.show(),h=l?"Please enter RN.<br><br>":"",h+="Numbers only.",$("#addAbsenceDialog #rnField .tooltip").html(h),m.addClass("auraRed"));var m=$("#addAbsenceDialog table .hours"),c=c=="Teachers"?"7":m.val(),l=$("#addAbsenceDialog table td #hoursError"),n=isEmpty(c),h=/^[0-9]+$/g,o=!n&&g.match(h);o?j.hide():(l.show(),h=n?"Please enter Hours.<br><br>":"",h+="Numbers only.",$("#addAbsenceDialog #hoursField .tooltip").html(h),m.addClass("auraRed"));k&&
e&&o&&(e=thisPage.getSelectedDate(),h=e.getTimezoneOffset()/60*-1,e.setHours(h,0,0,0),d=f?a:d.toUpperCase(),a={type:"POST",employmentType:$("#searchResultsContainer .label .title .text").html(),date:e.getTime(),rn:parseInt(g),name:d,hours:parseInt(c)},querySite("add",a,function(a){$("#addAbsenceDialog table select option:selected").html();thisPage.fillInCalendarSelect(a,d);$("#addAbsenceDialog").dialog("close");$("#calendarSelect select").change()}))},Cancel:function(){$(this).dialog("close")}}})},
clearAura:function(a){a.removeClass("auraSelected");a.removeClass("auraRed");a.removeClass("auraGreen");a.removeClass("auraLightBlue")},employmentTypeSelect:function(){var a=[],b=$("#searchResultsContainer .label .title .text").html();b!="Classified Employees"&&a.push({name:"Classified Employees",action:function(){thisPage.hideSearchResults();$("#searchResultsContainer .label span.text").html("Search Results:");$("#searchResults").html("");var a=$("#searchResultsContainer .label .title .text");a.html("Classified Employees");
a.removeClass("teacherView");a.addClass("classifiedEmployeeView");a=$("body");a.removeClass();a.addClass("classifiedBody");$("#calendarHeader .header .text").hide();$("#calendarHeader .header #importButton").hide();a={type:"POST",query:"",employmentType:$("#searchResultsContainer .label .title .text").html()};querySite("search",a,function(a){thisPage.fillInCalendarSelect(a,"");$("#calendarHeader #calendarSelect select").change()})},data:{}});b!="Teachers"&&a.push({name:"Teachers",action:function(){thisPage.hideSearchResults();
$("#searchResultsContainer .label span.text").html("Search Results:");$("#searchResults").html("");var a=$("#searchResultsContainer .label .title .text");a.html("Teachers");a.removeClass("classifiedEmployeeView");a.addClass("teacherView");a=$("body");a.removeClass();a.addClass("teacherBody");$("#calendarHeader .header .text").show();$("#calendarHeader .header #importButton").show();a={type:"POST",query:"",employmentType:$("#searchResultsContainer .label .title .text").html()};querySite("search",a,
function(a){thisPage.fillInCalendarSelect(a,"");$("#calendarHeader #calendarSelect select").change()})},data:{}});thisPage.displayPopupMenu(this,a)},getSelectedDate:function(){var a=parseInt($("#calendar .year .text").html()),b=parseInt($("#calendar #selectedMonth").val()),c=parseInt($("#calendar #selectedDay").val());return new Date(a,b,c)},loadMasterCalendar:function(){var a={type:"POST",searchBy:"year",year:parseInt($("#calendar .year .text").html()),employmentType:$("#searchResultsContainer .label .title .text").html()};
querySite("search",a,function(a){thisPage.fillInMasterCalendar(a)})},yearChange:function(a){$("#calendar .year .text").html(a);$("#calendar .month .day").attr("title","");$("#calendar .weekend").removeClass("weekend");$("#calendar .absentDay").removeClass("absentDay");$("#calendar .day .mask").removeClass("formSubmitted");$("#calendar .dayPlaceHolder").remove();var b=new Date(a,1,1),c=(new Date(a,1,29)).getDate()==29;$.each($("#calendar .month"),function(){var a=parseInt($(this).attr("id").replace("month_",
""));b.setMonth(a);b.setDate(1);var e=b.getDay(),f=$(this).children("#day_1");for(i=0;i<e;i++){var g='<div class="day dayPlaceHolder"><div class="mask">&nbsp;</div></div>';f.before(g)}a==1&&(c?$(this).children("#day_28").after('<div class="day dayOfMonth" id="day_29"><input class="absenceId" type="hidden" value=""><div class="mask">29</div></div>'):$(this).children("#day_29").remove());$.each($(this).children(".dayOfMonth"),function(){b.setDate(parseInt($(this).children(".mask").html()));var a=b.getDay();
(a==0||a==6)&&$(this).addClass("weekend")})});$("#calendarHeader #calendarSelect select").change()},run:function(){},mouseDown:function(){$(this).addClass("ui-state-active")},mouseUp:function(){$(this).removeClass("ui-state-active")},hoverOn:function(){$(this).addClass("ui-state-hover")},hoverOff:function(){$(this).removeClass("ui-state-hover")},hideSearchResults:function(){var a=$("#searchResultsContainer .tableContainer"),b=parseInt(a.css("min-height").replace("px",""));parseInt(a.css("height").replace("px",
""))!=b&&a.animate({height:b},250,function(){});a=$("#searchResultsContainer .label span#icon");a.removeClass("ui-state-active");a=a.children(".ui-icon");a.removeClass("ui-icon-triangle-1-n");a.addClass("ui-icon-triangle-1-s")},showSearchResults:function(){var a=$("#searchResultsContainer .tableContainer");parseInt(a.css("height").replace("px",""))==parseInt(a.css("min-height").replace("px",""))&&a.animate({height:200},250,function(){});a=$("#searchResultsContainer .label span#icon");a.removeClass("ui-state-active");
a=a.children(".ui-icon");a.removeClass("ui-icon-triangle-1-s");a.addClass("ui-icon-triangle-1-n")},clearSearchResults:function(){$("#searchResultsContainer #searchResults").html('<tr><th id="formSubmitted" class="ui-widget-header">Form</th><th id="date" class="ui-widget-header">Date</th><th id="name" class="ui-widget-header">Name</th><th id="info" class="ui-widget-header">Info</th></tr>')},displaySearchResult:function(a){var b=a.isDuplicate=="true"?"background-color:green;":"",c=a.formSubmitted?'checked="checked"':
"",d;a.date==null?d="":(d=new Date(a.date),d=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][d.getUTCMonth()]+" "+d.getUTCDate()+" "+d.getUTCFullYear());var e=a.duplicate?"Absence already exists. ":"",f="";a.action=="add"?f="Successfully added absence.":a.action=="update"?f="Successfully updated absence.":a.action=="remove"?f="Successfully removed absence.":a.action=="search"&&(f="");var g="";a.error==null?(a.error=f,g="ui-state-active"):g="ui-state-error";a=$('<tr class="item" style="'+
b+'"><input id="absenceId" type="hidden" value="'+a.id+'"><td id="formSubmitted"><input type="checkbox"'+c+'></td><td id="date">'+d+'</td><td id="name">'+a.name+'</td><td id="info" class="'+g+'">'+e+a.error+"</td></tr>");a.click(function(){if($("#calendarHeader #calendarSelect select").val()!=""){var a=$(this).children("#absenceId").val();$("#calendarHeader #calendarSelect select option[value='"+a+"']").attr("selected",!0);$("#calendarHeader #calendarSelect select").change()}});a.dblclick(function(){if($("#calendarHeader #calendarSelect select").val()==
""){var a=$(this).children("#name").html().trim();$("#calendarHeader #calendarSelect select option[value='"+a+"']").attr("selected",!0);$("#calendarHeader #calendarSelect select").change()}});a.hoverIntent(thisPage.hoverOn,thisPage.hoverOff);a.children("#formSubmitted").children("input").click(function(){var a={type:"POST",id:parseInt($(this).parent("#formSubmitted").parent(".item").children("input#absenceId").val()),formSubmitted:this.checked};querySite("complete",a,function(){var a=0,c=0;$.each($("#searchResults .item #formSubmitted input"),
function(){$(this).attr("checked")&&a++;c++});var b=parseInt($("#calendar .year .text").html()),d=parseInt($("#calendar #selectedMonth").val()),e=parseInt($("#calendar #selectedDay").val()),b=new Date(b,d,e,0,0,0,0),b=$("#month_"+b.getUTCMonth()+" #day_"+b.getUTCDate());a==c?b.children(".mask").addClass("formSubmitted"):b.children(".mask").removeClass("formSubmitted")})});$("#searchResultsContainer #searchResults").append(a);thisPage.showSearchResults()},fillInCalendarSelect:function(a,b){var c=$("#calendarHeader #calendarSelect select");
c.html("");$("#calendarHeader .header .title").html("Master Calendar");var d='<option value="" selected="selected">Master Calendar</option>',e=isEmpty(b),f=[];isEmpty(a)||$.each(a,function(){if($.inArray(this.name,f)==-1){var a="";!e&&b==this.name&&(a='selected="selected"');d+='<option value="'+this.name+'" '+a+">"+this.name+"</option>";f.push(this.name)}});c.html(d)},fillInMasterCalendar:function(a){$("#calendar .month .day").attr("title","");$("#calendar .month .absentDay").removeClass("absentDay");
$("#calendar .month .day .mask").removeClass("formSubmitted");var b={};$.each(a,function(){var a=new Date(this.date);a.getUTCFullYear()==parseInt($("#calendar .year .text").html())&&($("#month_"+a.getUTCMonth()+" #day_"+a.getUTCDate()).addClass("absentDay"),isEmpty(b[this.date])?b[this.date]={submitted:this.formSubmitted?1:0,total:1}:(b[this.date].total+=1,this.formSubmitted&&(b[this.date].submitted+=1)))});$.each(b,function(a,b){if(b.submitted==b.total){var e=new Date(parseInt(a)),f=e.getTimezoneOffset()/
60;e.setUTCHours(f,0,0,0);$("#month_"+e.getUTCMonth()+" #day_"+e.getUTCDate()+" .mask").addClass("formSubmitted")}});$("#calendarHeader .header img").hide()},search:function(){var a={type:"POST",query:$("#header #searchQuery").val(),employmentType:$("#searchResultsContainer .label .title .text").html()};$("#header #searchBar img").show();querySite("search",a,function(a){isEmpty(a)?($("#searchResultsContainer #searchResults").html('<tr class="searchResultEmpty"><td>No results found.</td></tr>'),a=
$("#searchResultsContainer .label .ui-icon"),a.removeClass("ui-icon-triangle-1-s"),a.addClass("ui-icon-triangle-1-n"),thisPage.showSearchResults()):(thisPage.clearSearchResults(),$.each(a,function(a){this.action="search";thisPage.displaySearchResult(this,a)}));$("#searchResultsContainer .label span.text").html("Search Results:");$("#header #searchBar img").hide();$("#searchResults #formSubmitted").hide();$("#searchResults #date").hide();$("#searchResults #info").hide()})},calendarSelected:function(){var a=
{name:$("#calendarSelect select option:selected").text(),employmentType:$("#searchResultsContainer .label .title .text").html()};$("#calendarHeader .header img").show();$("#calendarHeader .header .title").html(a.name);a.name=="Master Calendar"?thisPage.loadMasterCalendar():querySite("get",a,function(a){$("#calendar .month .day").attr("title","");$("#calendar .month .absentDay").removeClass("absentDay");$("#calendar .month .day .mask").removeClass("formSubmitted");$.each(a,function(){var a=new Date(this.date);
a.getUTCFullYear()==parseInt($("#calendar .year .text").html())&&(a=$("#month_"+a.getUTCMonth()+" #day_"+a.getUTCDate()),a.addClass("absentDay"),a.children(".absenceId").val(this.id),a.attr("title","RN: "+this.rn),this.formSubmitted&&a.children(".mask").addClass("formSubmitted"))});thisPage.hideSearchResults();$("#calendarHeader .header img").hide()})},budgetImport:function(){var a=$("#calendarHeader textarea");isEmpty(a.val())?a.is(":visible")?(a.hide(),$("#importButton span").html("Import")):(a.show(),
$("#importButton span").html("Submit"),$("#calendarHeader textarea").focus(),thisPage.hideSearchResults()):(a={type:"POST",rawText:a.val(),year:parseInt($("#calendar .year .text").html()),employmentType:$("#searchResultsContainer .label .title .text").html().trim()},$("#calendarHeader .header img").show(),$("#calendarHeader textarea").val(""),$("#calendarHeader textarea").hide(),$("#calendarHeader #importButton span").html("Import"),$("#searchResultsContainer .label span.text").html("Import Results:"),
thisPage.clearSearchResults(),querySite("parse",a,function(a){var c=[],d=[];$.each($("#calendarHeader #calendarSelect option"),function(){var a=$(this).html();if("Master Calendar"!=a){var b={id:$(this).val(),name:a};c.push(b);d.push(a)}});var e=[];$.each(a,function(a){$.inArray(this.name,e)==-1&&(thisPage.displaySearchResult(this,a),e.push(this.name),$.inArray(this.name,d)==-1&&(c.push({id:this.id,name:this.name}),d.push(name)))});c.sort(function(a,b){return a.name>b.name?1:0});thisPage.fillInCalendarSelect(c,
"");$("#searchResultsContainer #searchResults").focus();$("#calendarHeader .header img").hide();$("#calendarHeader #calendarSelect select").change();$("#searchResults #formSubmitted").hide()}))},dayClick:function(){$("#calendar #selectedMonth").val(parseInt($(this).parent(".month").attr("id").replace("month_","")));$("#calendar #selectedDay").val(parseInt($(this).attr("id").replace("day_","")));if($(this).hasClass("absentDay"))if($("#calendarHeader #calendarSelect select").val()=="")thisPage.listAbsences();
else{var a=$(this).children(".mask"),b=parseInt($(this).children("input").val()),c={};a.hasClass("formSubmitted")?(c={type:"POST",id:b,formSubmitted:!1},b=function(){a.removeClass("formSubmitted")}):(c={type:"POST",id:b,formSubmitted:!0},b=function(){a.addClass("formSubmitted")});querySite("complete",c,b)}},listAbsences:function(){var a={type:"POST",searchBy:"date",query:parseInt($("#calendar #selectedMonth").val())+1+"-"+$("#calendar #selectedDay").val()+"-"+$("#calendar .year .text").html(),employmentType:$("#searchResultsContainer .label .title .text").html().trim()};
querySite("search",a,function(a){a!=null&&(thisPage.clearSearchResults(),$.each(a,function(a){this.action="search";thisPage.displaySearchResult(this,a)}));$("#calendarHeader .header img").hide();$("#searchResults .item #formSubmitted").show();a=thisPage.getSelectedDate();$("#searchResultsContainer .label span.text").html("Absences for "+$.format.date(a,"MMM dd, yyyy"));$("#calendarSelect select option:first").attr("selected",!0);$("#calendarSelect select").change();$("#searchResults #info").removeClass("ui-state-active");
thisPage.showSearchResults()})},removeAbsence:function(){if(confirm("Are you sure you want to remove this absence?")){var a=$(this).data("data");querySite("remove",{type:"POST",id:a.absenceId},function(){$("#"+a.monthDomId+" #"+a.dayDomId).removeClass("absentDay");$("#"+a.monthDomId+" #"+a.dayDomId+" .mask").removeClass("formSubmitted")})}},addAbsence:function(){$("#addAbsenceDialog").dialog("open")},displayUserMenu:function(a){a.preventDefault();menuItemList=[];menuItemList.push({name:"Logout",action:function(){window.location=
$("#appNavBar #userNavItem .logoutUrl").val()},data:{}});thisPage.displayPopupMenu(this,menuItemList)},displayDayMenu:function(a){$(this).hasClass("weekend")||(a.preventDefault(),$("#calendar #selectedMonth").val(parseInt($(this).parent(".month").attr("id").replace("month_",""))),$("#calendar #selectedDay").val(parseInt($(this).attr("id").replace("day_",""))),a=$("#calendarHeader #calendarSelect select").val()=="",menuItemList=[],(a||!$(this).hasClass("absentDay"))&&menuItemList.push({name:"Add Absence",
action:thisPage.addAbsence,data:{}}),$(this).hasClass("absentDay")&&!a&&menuItemList.push({name:"Remove Absence",action:thisPage.removeAbsence,data:{absenceId:parseInt($(this).children("input").val()),monthDomId:$(this).parent(".month").attr("id"),dayDomId:$(this).attr("id")}}),(!a||$(this).hasClass("absentDay"))&&menuItemList.push({name:"List Absences",action:thisPage.listAbsences,data:{}}),thisPage.displayPopupMenu(this,menuItemList))},displayPopupMenu:function(a,b){if(!isEmpty(b)){$("#popupMenu").remove();
var c=$('<div id="popupMenu" class="ui-widget-content"></div>');$.each(b,function(){var a=$('<div class="item">'+this.name+"</div>");a.click(this.action);a.data("data",this.data);c.append(a)});var d=$(a).offset();c.css("position","absolute");c.css("left",d.left);d=d.top+$(a).height()+parseInt($(a).css("padding-top").replace("px",""))+parseInt($(a).css("padding-bottom").replace("px",""));c.css("top",d);d=$('<div id="popupBackground"></div>');d.click(function(){$("#popupBackground").remove();$("#fileUploadMenu").remove()});
d.append(c);$("body").append(d)}},csvImport:function(a){a.preventDefault();var a=$('<div id="fileUploadMenu" class="ui-widget-content auraGreen"><form action="/import" method="POST" type="multipart/form-data"><input type="file" id="csvFile" name="csvFile"></form></div>'),b=$(this).offset();a.css("position","absolute");var c=b.top-parseInt($(this).parent().css("border-top-width").replace("px",""));a.css("top",c);b=b.left+$(this).width()+parseInt($(this).css("padding-left").replace("px",""))+parseInt($(this).css("padding-right").replace("px",
""));a.css("left",b);a.children("form").children("#csvFile").change(function(){$("#fileUploadMenu form").submit()});a.children("form").ajaxForm({dataType:"json",success:function(a){$("#searchResultsContainer .label span.text").html("Csv Import Results:");thisPage.clearSearchResults();$.each(a,function(a){thisPage.displaySearchResult(this,a)});$("#fileUploadMenu").remove();$("#searchResults #date").show();$("#searchResults #formSubmitted").hide();$("#popupBackground").click();$("#calendarHeader #calendarSelect select").change();
thisPage.fillInCalendarSelect(a,"")}});$("body").append(a);return!1},csvExport:function(){var a='<input name="employmentType" value="'+$("#searchResultsContainer .label .title .text").html()+'">';$("body").append('<form id="exportform" action="/export" method="post" target="_blank">'+a+"</form>");$("#exportform").submit().remove()}};
